### ISSUE TITLE
HTML

### ISSUE THREAD

**Issue by solohuck** [solohuck/prework-study-guide#1]
# HTML

## User Story
As a bootcamp student
I want the prework notes to be structured on a webpage
so that I can easily find and read information 

## Acceptance Criteria 
GIVEN a prework Study Guide website
WHEN I visit the website in my browser 
THEN I see four boxes titled HTML, CSS, GIT, and JavaScript with associated notes listed

**Comment by Shubham56-droid** [comment]
i would like to work on this issue but can you please proive details about what study notes and how u want to structure it on webpage ??

**Comment by solohuck** [comment]
The study notes will be from all the notes I have taken during my prework sessions. The structure will be basic and have 4 main headers like HTML, CSS, Git, and JavaScript.
