### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by solohuck** [solohuck/prework-study-guide#2]
# CSS 

## User Story 
As a boot camp student 
I want the prework notes to be structed on a webpage
So that I can easily find and read the Information

## Acceptance Criteria 
GIVEN a Prework Study Guide website
WHEN I view the study guide
THEN I see a dark blue header and footer, and four boxes with a shadow

**Comment by Shubham56-droid** [comment]
i would like to work on this issue but can you please proive details about what study notes and how u want to structure it on webpage ??
